# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\"\x07\n\x05\x45mpty\"-\n\x10\x43lientIdentifier\x12\x19\n\x11\x63lient_identifier\x18\x01 \x01(\x05\"#\n\x0fMessageReceived\x12\x10\n\x08response\x18\x01 \x01(\t\"p\n\rMessageFormat\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x19\n\x11\x63lient_identifier\x18\x02 \x01(\x05\x12\x14\n\x0cmessage_text\x18\x03 \x01(\t\x12\x1a\n\x12server_port_number\x18\x04 \x01(\x05\" \n\nClientName\x12\x12\n\nfirst_name\x18\x01 \x01(\t\"!\n\nPortNumber\x12\x13\n\x0bport_number\x18\x01 \x01(\x05\x32\x81\x02\n\x0b\x43hatService\x12\x39\n\x0bSendMessage\x12\x13.main.MessageFormat\x1a\x15.main.MessageReceived\x12;\n\nGetMessage\x12\x16.google.protobuf.Empty\x1a\x13.main.MessageFormat0\x01\x12\x39\n\rGetPortNumber\x12\x16.google.protobuf.Empty\x1a\x10.main.PortNumber\x12?\n\x13GetClientIdentifier\x12\x10.main.ClientName\x1a\x16.main.ClientIdentifierb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=49
  _EMPTY._serialized_end=56
  _CLIENTIDENTIFIER._serialized_start=58
  _CLIENTIDENTIFIER._serialized_end=103
  _MESSAGERECEIVED._serialized_start=105
  _MESSAGERECEIVED._serialized_end=140
  _MESSAGEFORMAT._serialized_start=142
  _MESSAGEFORMAT._serialized_end=254
  _CLIENTNAME._serialized_start=256
  _CLIENTNAME._serialized_end=288
  _PORTNUMBER._serialized_start=290
  _PORTNUMBER._serialized_end=323
  _CHATSERVICE._serialized_start=326
  _CHATSERVICE._serialized_end=583
# @@protoc_insertion_point(module_scope)
