# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\"\x07\n\x05\x45mpty\"-\n\x10\x43lientIdentifier\x12\x19\n\x11\x63lient_identifier\x18\x01 \x01(\x05\"#\n\x0fMessageReceived\x12\x10\n\x08response\x18\x01 \x01(\t\"T\n\rMessageFormat\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x19\n\x11\x63lient_identifier\x18\x02 \x01(\x05\x12\x14\n\x0cmessage_text\x18\x03 \x01(\t\" \n\nClientName\x12\x12\n\nfirst_name\x18\x01 \x01(\t2\xc6\x01\n\x0b\x43hatService\x12\x39\n\x0bSendMessage\x12\x13.main.MessageFormat\x1a\x15.main.MessageReceived\x12;\n\nGetMessage\x12\x16.google.protobuf.Empty\x1a\x13.main.MessageFormat0\x01\x12?\n\x13GetClientIdentifier\x12\x10.main.ClientName\x1a\x16.main.ClientIdentifierb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_CLIENTIDENTIFIER = DESCRIPTOR.message_types_by_name['ClientIdentifier']
_MESSAGERECEIVED = DESCRIPTOR.message_types_by_name['MessageReceived']
_MESSAGEFORMAT = DESCRIPTOR.message_types_by_name['MessageFormat']
_CLIENTNAME = DESCRIPTOR.message_types_by_name['ClientName']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:main.Empty)
  })
_sym_db.RegisterMessage(Empty)

ClientIdentifier = _reflection.GeneratedProtocolMessageType('ClientIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTIDENTIFIER,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:main.ClientIdentifier)
  })
_sym_db.RegisterMessage(ClientIdentifier)

MessageReceived = _reflection.GeneratedProtocolMessageType('MessageReceived', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERECEIVED,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:main.MessageReceived)
  })
_sym_db.RegisterMessage(MessageReceived)

MessageFormat = _reflection.GeneratedProtocolMessageType('MessageFormat', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEFORMAT,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:main.MessageFormat)
  })
_sym_db.RegisterMessage(MessageFormat)

ClientName = _reflection.GeneratedProtocolMessageType('ClientName', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTNAME,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:main.ClientName)
  })
_sym_db.RegisterMessage(ClientName)

_CHATSERVICE = DESCRIPTOR.services_by_name['ChatService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=49
  _EMPTY._serialized_end=56
  _CLIENTIDENTIFIER._serialized_start=58
  _CLIENTIDENTIFIER._serialized_end=103
  _MESSAGERECEIVED._serialized_start=105
  _MESSAGERECEIVED._serialized_end=140
  _MESSAGEFORMAT._serialized_start=142
  _MESSAGEFORMAT._serialized_end=226
  _CLIENTNAME._serialized_start=228
  _CLIENTNAME._serialized_end=260
  _CHATSERVICE._serialized_start=263
  _CHATSERVICE._serialized_end=461
# @@protoc_insertion_point(module_scope)
